Name:           ros-indigo-ubiquity-motor
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS ubiquity_motor package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-controller-manager
Requires:       ros-indigo-diff-drive-controller
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-hardware-interface
Requires:       ros-indigo-joint-state-controller
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-serial
Requires:       ros-indigo-tf
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-controller-manager
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-hardware-interface
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-serial
BuildRequires:  ros-indigo-tf

%description
Provides a ROS interface to Ubiquity Robotics Magni motor controllers

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Mar 08 2016 Rohan Agrawal <rohan@aleopile.com> - 0.4.0-0
- Autogenerated by Bloom

* Sat Nov 28 2015 Rohan Agrawal <rohan@aleopile.com> - 0.3.2-0
- Autogenerated by Bloom

* Sun Oct 18 2015 Rohan Agrawal <rohan@aleopile.com> - 0.3.1-1
- Autogenerated by Bloom

* Mon Oct 12 2015 Rohan Agrawal <rohan@aleopile.com> - 0.3.1-0
- Autogenerated by Bloom

* Sun Sep 20 2015 Rohan Agrawal <rohan@aleopile.com> - 0.3.0-0
- Autogenerated by Bloom

* Sun Aug 09 2015 Rohan Agrawal <rohan@aleopile.com> - 0.2.0-0
- Autogenerated by Bloom

* Sun Mar 22 2015 Rohan Agrawal <rohan@aleopile.com> - 0.1.0-1
- Autogenerated by Bloom

* Sun Mar 22 2015 Rohan Agrawal <rohan@aleopile.com> - 0.1.0-0
- Autogenerated by Bloom

